### ISSUE TITLE
Doesn't work on Ruby 1.9 32bits

### ISSUE THREAD

**Issue by willemp** [jjyg/metasm#14]
Hi,

It seems that Ruby 1.9 (and likely 1.8) is broken (tested on 32bit Linux).

In particular the line:
#if #{nil.object_id == 4}

in metasm/dynldr.rb results in #if true on 1.8 and 1.9 but the c parser doesn't take that, so the #define TYPE for 2.0 is used, which results in a nice heisenbug, it works (mostly) if the pointers to the object don't have 0xc at the lowest nibble.

changing it to
#if #{nil.object_id == 4 ? "1" : "0"}
fixes that particular case.

Other places check RUBY_VERSION instead of nil.object_id. It can send pull, but it seems that 1.8 // 1.9 are no longer supported by Metasm?

**Comment by willemp** [comment]
Update, this is likely a 32bit vs 64bit problem. Ruby on 64bit uses FLONUMS. They is nil.object_id == 4 is true on systems that don't use FLONUM (i.e. 32bit systems, where a sizeof(uintptr_t) < sizeof(double)).

The fix is the same though, change to output #if 1 instead of #if true. (Tested on a 32bit Linux with ruby-2.1.5)

**Comment by jjyg** [comment]
Nice catch ! Fixed, thanks
