### ISSUE TITLE
[Feature Request] Make DEFAULT_INTERP configurable from Metasm::ELF.compile_c

### ISSUE THREAD

**Issue by bcoles** [jjyg/metasm#28]
Sorry if this doesn't make sense. Perhaps I'm going about it the wrong way.

Using `Metasm::ELF.compile_c` is really convenient. It's great.

Unfortunately the interpreters are hard coded constants in [metasm/exe_format/elf.rb](https://github.com/jjyg/metasm/blob/master/metasm/exe_format/elf.rb#L407):

```
        DEFAULT_INTERP = '/lib/ld-linux.so.2'
        DEFAULT_INTERP64 = '/lib64/ld-linux-x86-64.so.2'
```

These are incorrect for Solaris systems (tested 9, 10 and 11).

It would be great if there was an easy way to overwrite the default linker/interpreter for the generated ELF when calling `Metasm::ELF.compile_c`, rather than having to construct the executable from scratch, or monkey patching the library.

Executing a generated x86 ELF shared object on a Solaris system (tested on Solaris 10u11 x86) complains that `ld-linux.so.2` and `libc.so.6` are not present.

The shared object is valid and will run on the system, provided the right interpreter and needed libraries are available. I've verified this by making the following changes to the Solaris system:

```bash
cp /lib/ld.so.1 /lib/ld-linux.so.2
cp /lib/libc.so.1 /lib/libc.so.6
```

**Comment by bcoles** [comment]
Definitely going about it the wrong way. `gsub` for the win.

**Comment by jjyg** [comment]
You can use the following syntax from C :
asm { .interp "/lib/ld.so.1" }
