### ISSUE TITLE
metasm-shell.rb:40:in `encode': wrong number of arguments

### ISSUE THREAD

**Issue by fede333lago** [jjyg/metasm#36]
Hey guys, I installed the latest version of metasploit from the repos without any issue, and when I try to run the metasm-shell.rb I always get the same error. 

```
[+] Metasm assembly shell
type help for usage..

asm>
metasm-shell.rb:40:in `encode': wrong number of arguments (given 2, expected 0) (ArgumentError)
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6135:in `alloc_history_entry'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6168:in `add_history'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:54:in `readline'
        from metasm-shell.rb:72:in `asm'
        from metasm-shell.rb:101:in `<main>'
```
It doesn't matter If I run "help", an assembler line or just press enter, always the same error. Tried with the standalone version of metasm and exactly the same happens. My ruby version is 
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`

**Comment by jjyg** [comment]
Not quite sure what the issue is ; I suspect a conflicting definition of String.encode declared in some other lib. I renamed the one used in metasm-shell to 'asm_encode', that should fix it.
