### ISSUE TITLE
install notes may be outdated

### ISSUE THREAD

**Issue by goatshriek** [jjyg/metasm#43]
In trying to make sure I used the latest version of metasm, I followed the notes in `doc/install_notes.txt` and tried to clone the mercurial repo (`hg clone http://metasm.cr0.org/hg/metasm/`), but this gives me an HTTP 404 error. After trying a few other variations on that URL and the project website URL, I'm wondering if that document just needs to be updated to point at this github repo instead?

I'm happy to update the install notes as I go through them and submit a PR, but I just want to make sure that I'm not missing something before I take the time to make updates that are wrong/won't be accepted. I'm admittedly not very familiar with mercurial, so it's possible that I'm doing something dumb.

**Comment by goatshriek** [comment]
Just a quick staleness check on this - if this is the wrong place for stuff like this I can go ahead and close this.

**Comment by jjyg** [comment]
Thanks for the heads up, fixed in 2f30431
